language: node_js
sudo: false
dist: trusty
node_js:
  "10"

cache:
  directories:
    - node_modules

addons:
  chrome: stable


#before_script:

script:
  - node_modules/@angular/cli/bin/ng test --source-map false  --watch false --browsers ChromeHeadless  --code-coverage

notifications:
  slack: ipponforge:POZIxDUMmeddHxK10Ub78v8j

before_deploy:
  - node_modules/@angular/cli/bin/ng build --prod

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_KEY
  on:
    branch: master
